version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      PORT: '8080'
      DB_USER: 'root'
      DB_PASSWORD: 'password'
      DB_HOST: 'db'
      DB_PORT: '3306'
      DB_NAME: 'projectmanager'
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: 'password'
      MYSQL_DATABASE: 'projectmanager'
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
